"""Verify NeuroAM's electrode placement against a hand-built lab montage.

Three arms, all on the same 83 µm rat head-and-eye crop:

  A  REFERENCE  — the lab's ``..._CLStim_JGND_..._with_retina`` model, whose
                  electrodes were painted by hand in ModelTool.
  B  REPLAY     — the raw (no-electrode) model + the reference electrode voxels
                  stamped back in.  Must reproduce A exactly; this isolates
                  "is the raw model the same base?" from any geometry question.
  C  PARAMETRIC — the raw model + electrodes **generated by NeuroAM** from a
                  fitted spec (spherical band + swept tube + sheath).  This is
                  the arm that tests the placement code.

Each arm is assembled, solved for a unit-current field, and compared on:
geometry (Dice), retinal/ocular dose, and voxel-wise field agreement.

Run:  python examples/05_electrode_placement_verification.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np

from neuroam import electrodes as el
from neuroam.assembly import assemble_uniform
from neuroam.fields import (current_density, efield, node_grid, roi_metrics,
                            voxel_average)
from neuroam.materials import Material, MaterialLibrary
from neuroam.model import VoxelModel, Source
from neuroam.solver import kcl_report, solve, unit_current_vector

HERE = Path(__file__).resolve().parent
SAMP = HERE.parent / "samples" / "ratcc_eye_83um"
OUT = SAMP / "verification"
OUT.mkdir(parents=True, exist_ok=True)

WORLD = (180, 160, 220)
CROP_OFFSET = np.array([230, 290, 150])      # crop -> full-model coords
DX = 83e-6
RETINA, VITREOUS = 77, 55
STIM, GND, INSUL = 101, 102, 110


def load_labels(path) -> np.ndarray:
    nx, ny, nz = WORLD
    return np.ascontiguousarray(
        np.loadtxt(path).reshape(nz, ny, nx).transpose(2, 1, 0)).astype(np.int32)


def build_model(labels, name) -> VoxelModel:
    lib = MaterialLibrary.from_in_file(
        SAMP / "RatCC_eye_180_160_220_83um_with_retina.in")
    return VoxelModel(labels=labels.copy(), dx=DX, materials=lib, name=name)


def solve_arm(model, node_stim, node_gnd, tag, progress=print):
    """Solve one arm and return only the field arrays (frees the system)."""
    import gc

    model.sources = [Source(name="Cur1", node=tuple(node_stim))]
    model.ground_nodes = [tuple(node_gnd)]
    sysm = assemble_uniform(model)
    progress(f"  [{tag}] {sysm.n:,} unknowns, {sysm.G.nnz:,} nnz")
    I = unit_current_vector(sysm, "Cur1")
    res = solve(sysm, I, method="cg", rtol=1e-8, precond="amg")
    rep = kcl_report(sysm, res.v, I)
    progress(f"  [{tag}] {res.iterations} iters, residual {res.residual:.2e}, "
             f"{res.seconds:.0f}s, KCL {rep['relative_residual']:.1e}")
    grid = node_grid(sysm, res.v)
    out = dict(iterations=res.iterations, residual=res.residual,
               kcl=rep["relative_residual"], vavg=voxel_average(grid))
    del sysm, I, res
    gc.collect()
    Ex, Ey, Ez, Emag = efield(grid, model.dx)
    del grid
    gc.collect()
    Jx, Jy, Jz, Jmag = current_density(model, Ex, Ey, Ez)
    del Ex, Ey, Ez, Jx, Jy, Jz
    gc.collect()
    out["Emag"] = Emag.astype(np.float32)
    out["Jmag"] = Jmag.astype(np.float32)
    out["vavg"] = out["vavg"].astype(np.float32)
    del Emag, Jmag
    gc.collect()
    return out


def agreement(a, b, mask, label):
    """Field agreement between two arms over a mask."""
    x, y = a[mask].ravel(), b[mask].ravel()
    denom = np.linalg.norm(x)
    return {
        "region": label,
        "voxels": int(mask.sum()),
        "mean_a": float(x.mean()), "mean_b": float(y.mean()),
        "mean_ratio_b_over_a": float(y.mean() / x.mean()) if x.mean() else None,
        "relative_L2_difference": float(np.linalg.norm(y - x) / denom) if denom else None,
        "pearson_r": float(np.corrcoef(x, y)[0, 1]),
        "max_abs_rel_diff": float(np.max(np.abs(y - x) / np.maximum(np.abs(x), 1e-30))),
    }


def main():
    report = {"world": list(WORLD), "unit_voxel_m": DX,
              "crop_offset_in_full_model": CROP_OFFSET.tolist()}

    print("loading crops ...")
    lab_ref = load_labels(SAMP / "RatCC_eye_180_160_220_83um_with_retina.model")
    lab_raw = load_labels(SAMP / "RatCC_eye_180_160_220_83um_RAW_no_electrodes.model")

    ref_masks = {m: (lab_ref == m) for m in (STIM, GND, INSUL)}
    print("  reference electrode voxels:",
          {m: int(v.sum()) for m, v in ref_masks.items()})
    # the raw model must contain no electrode labels at all
    raw_has = {m: int((lab_raw == m).sum()) for m in (STIM, GND, INSUL)}
    print("  raw model electrode voxels:", raw_has)
    report["raw_model_electrode_voxels"] = raw_has

    # where the two crops differ at all
    diff = lab_ref != lab_raw
    print(f"  voxels differing ref vs raw: {int(diff.sum()):,} "
          f"(electrode voxels: {sum(int(v.sum()) for v in ref_masks.values()):,})")
    report["voxels_differing_ref_vs_raw"] = int(diff.sum())

    # ---------------- arm B: exact replay ----------------
    lab_replay = lab_raw.copy()
    for m, msk in ref_masks.items():
        lab_replay[msk] = m
    exact = bool((lab_replay == lab_ref).all())
    print(f"\n[B] replay reproduces reference exactly: {exact}")
    report["replay_exact"] = exact

    # ---------------- arm C: parametric placement ----------------
    spec = json.loads((SAMP.parent / "electrode_ref" / "fitted_specs.json").read_text())
    specs = []
    for e in spec["electrodes"]:
        p = dict(e["params"])
        if "path" in p:
            p["path"] = (np.asarray(p["path"]) - CROP_OFFSET).tolist()
        if "center" in p:
            p["center"] = (np.asarray(p["center"]) - CROP_OFFSET).tolist()
        ins = None
        if e.get("insulation"):
            ins = json.loads(json.dumps(e["insulation"]))
            ins["params"]["path"] = (np.asarray(ins["params"]["path"])
                                     - CROP_OFFSET).tolist()
        specs.append(el.ElectrodeSpec(
            name=e["name"], role=e["role"], material=e["material"],
            shape=e["shape"], params=p, insulation=ins, grid=e.get("grid", 1),
            waveform=e.get("waveform")))

    model_C = build_model(lab_raw, "ratcc_eye_parametric")
    masks_C = el.place(model_C, specs, register=False)
    geom = []
    for nm, m, ref in (("CL_stim (101)", masks_C["CL_stim"], ref_masks[STIM]),
                       ("J_ground (102)", masks_C["J_ground"], ref_masks[GND]),
                       ("insulation (110)", masks_C.get("J_ground:insulation"),
                        ref_masks[INSUL])):
        if m is None:
            continue
        g = el.compare_masks(m, ref, nm)
        geom.append(g)
        print(f"[C] {nm:18s} dice {g['dice']:.4f}  "
              f"gen {g['generated_voxels']:5d} / ref {g['reference_voxels']:5d}")
    report["geometry"] = geom

    # ---------------- solve all three ----------------
    # pin the same injection/return nodes in every arm so the comparison is
    # about geometry, not about which metal voxel carries the source
    both_stim = ref_masks[STIM] & masks_C["CL_stim"]
    both_gnd = ref_masks[GND] & masks_C["J_ground"]
    node_stim = tuple(int(v) for v in np.argwhere(both_stim)[len(np.argwhere(both_stim)) // 2])
    node_gnd = tuple(int(v) for v in np.argwhere(both_gnd)[len(np.argwhere(both_gnd)) // 2])
    print(f"\nshared nodes: stim {node_stim} (full "
          f"{tuple(np.array(node_stim)+CROP_OFFSET)}), gnd {node_gnd}")
    report["nodes"] = {"stim_crop": list(node_stim), "gnd_crop": list(node_gnd)}

    arms = {}
    print("\nsolving ...")
    # Arm B needs no solve: its label array is bit-identical to A's (checked
    # above), and the assembled system is a pure function of labels, materials
    # and dx — so an identical matrix and an identical field follow.  Solving
    # it would only re-measure the solver's own determinism.
    arms["A_reference"] = solve_arm(build_model(lab_ref, "ref"), node_stim,
                                    node_gnd, "A")
    arms["C_parametric"] = solve_arm(model_C, node_stim, node_gnd, "C")

    # ---------------- compare ----------------
    regions = {
        "retina": lab_ref == RETINA,
        "vitreous": lab_ref == VITREOUS,
        "eye (retina+vitreous)": np.isin(lab_ref, [RETINA, VITREOUS]),
        "whole crop (tissue)": ~np.isin(lab_ref, [0, STIM, GND, INSUL]),
    }
    A = arms["A_reference"]
    report["dose_per_unit_A"] = {
        k: [roi_metrics(m, arm["Emag"], arm["Jmag"], name=nm)
            for nm, m in regions.items()]
        for k, arm in arms.items()}

    comp = {}
    for arm in ("C_parametric",):
        comp[arm] = [agreement(A["Jmag"], arms[arm]["Jmag"], m, nm)
                     for nm, m in regions.items()]
    report["field_agreement_vs_reference_Jmag"] = comp

    print("\n--- retinal dose (per 1 A injected) ---")
    for k, arm in arms.items():
        r = [x for x in report["dose_per_unit_A"][k] if x["name"] == "retina"][0]
        print(f"  {k:14s} E_mean {r['E_mean_V_per_m']:.4g} V/m   "
              f"J_mean {r['J_mean_A_per_m2']:.4g} A/m²   "
              f"E_p95 {r['E_p95_V_per_m']:.4g}")
    print("\n--- |J| agreement vs reference ---")
    for arm, rows in comp.items():
        for r in rows:
            print(f"  {arm:14s} {r['region']:22s} rel-L2 {r['relative_L2_difference']:.3e}  "
                  f"r={r['pearson_r']:.6f}  mean ratio {r['mean_ratio_b_over_a']:.4f}")

    np.savez_compressed(OUT / "fields.npz",
                        labels_ref=lab_ref, labels_raw=lab_raw,
                        labels_param=model_C.labels,
                        Jmag_A=A["Jmag"], Jmag_C=arms["C_parametric"]["Jmag"],
                        Emag_A=A["Emag"], Emag_C=arms["C_parametric"]["Emag"],
                        vavg_A=A["vavg"], vavg_C=arms["C_parametric"]["vavg"])
    (OUT / "verification_report.json").write_text(json.dumps(report, indent=2))
    print(f"\nwrote {OUT/'verification_report.json'} and fields.npz")
    return report


if __name__ == "__main__":
    main()
