"""SWC morphology I/O and synthetic test morphologies.

A ``.swc`` file is the standard neuron-reconstruction format: one row per
traced point — ``id type x y z radius parent`` (space-separated, ``#``
comments, 1-indexed ids, ``parent=-1`` for roots) — in micrometers. This
module reads that tree directly (rather than reconstructing it from a live
NEURON model's sections/segments) because it is what a real morphology
actually looks like: a dense, smoothly-traced skeleton, not a handful of
compartment centers. Simulated per-segment values (Vm, ``|E|``, ...) are then
mapped onto it by nearest neighbor, the same approach the lab's own
``neuron_exstim.visualize`` module uses for its SWC-based Vm animations.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import numpy as np


@dataclass
class SWCMorphology:
    """A traced morphology: one row per point, in micrometers."""

    ids: np.ndarray         # (n,) int, 1-indexed as in the file
    types: np.ndarray       # (n,) int SWC type (1 soma, 2 axon, 3 basal dend, 4 apical, ...)
    xyz_um: np.ndarray      # (n, 3) float
    radius_um: np.ndarray   # (n,) float
    parent: np.ndarray      # (n,) int, ids.dtype; -1 for roots

    def __len__(self) -> int:
        return len(self.ids)

    def edges(self) -> np.ndarray:
        """(n_edges, 2) row-indices (not ids) of each point to its parent."""
        id_to_row = {int(i): r for r, i in enumerate(self.ids)}
        rows = []
        for r, p in enumerate(self.parent):
            if p in id_to_row and id_to_row[p] != r:
                rows.append((r, id_to_row[p]))
        return np.asarray(rows, dtype=np.int64).reshape(-1, 2)

    def recentered(self, at: Optional[np.ndarray] = None) -> np.ndarray:
        """Points translated so the first (root/soma) point sits at ``at``
        (default: origin) — the natural anchor for registration, matching
        how compartment coordinates are conventionally referenced to the
        soma."""
        origin = self.xyz_um[0]
        target = np.zeros(3) if at is None else np.asarray(at, dtype=float)
        return self.xyz_um - origin + target


def read_swc(path) -> SWCMorphology:
    ids, types, xs, ys, zs, rs, parents = [], [], [], [], [], [], []
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 7:
            continue
        i, t, x, y, z, r, p = parts[:7]
        ids.append(int(i)); types.append(int(t))
        xs.append(float(x)); ys.append(float(y)); zs.append(float(z))
        rs.append(float(r)); parents.append(int(p))
    if not ids:
        raise ValueError(f"{path}: no SWC rows found")
    return SWCMorphology(
        ids=np.asarray(ids, dtype=np.int64),
        types=np.asarray(types, dtype=np.int64),
        xyz_um=np.stack([xs, ys, zs], axis=1).astype(float),
        radius_um=np.asarray(rs, dtype=float),
        parent=np.asarray(parents, dtype=np.int64),
    )


def write_swc(path, morph: SWCMorphology) -> Path:
    lines = ["# generated by neuroam.morphology"]
    for i, t, (x, y, z), r, p in zip(morph.ids, morph.types, morph.xyz_um,
                                     morph.radius_um, morph.parent):
        lines.append(f"{i} {t} {x:.4f} {y:.4f} {z:.4f} {r:.4f} {p}")
    Path(path).write_text("\n".join(lines) + "\n")
    return Path(path)


def estimate_depth_axis(morph: SWCMorphology, soma_type: int = 1,
                        dendrite_type: int = 3,
                        local_types: Sequence[int] = (1, 3, 5, 6, 7)) -> np.ndarray:
    """Unit vector, in the morphology's own local (untransformed) frame,
    pointing from the soma toward the dendritic arbor.

    A laminar cell like a retinal ganglion cell is thin along exactly this
    axis (soma in the ganglion cell layer, dendrites reaching into the
    inner plexiform layer one side, axon leaving for the nerve fiber layer
    the other) — anatomically, this is the axis that should end up
    perpendicular to the retina wherever the cell sits, regardless of the
    globe's local curvature there.

    Found by PCA (the least-variance principal axis) restricted to
    ``local_types`` — soma + dendrites + the short proximal-axon regions,
    deliberately excluding the bulk of the distal axon, which runs
    tangentially for hundreds of micrometers once it reaches the nerve
    fiber layer and would otherwise dominate the estimate with an
    in-plane, not through-plane, direction. The sign is then corrected so
    the axis points soma → dendrites, not the reverse (PCA alone doesn't
    know which end is which).
    """
    local = np.isin(morph.types, np.asarray(local_types))
    pts = morph.xyz_um[local]
    if len(pts) < 3:
        raise ValueError("too few points to estimate a depth axis")
    centered = pts - pts.mean(axis=0)
    _, _, Vt = np.linalg.svd(centered, full_matrices=False)
    axis = Vt[-1]

    soma_c = morph.xyz_um[morph.types == soma_type].mean(axis=0)
    dend_c = morph.xyz_um[morph.types == dendrite_type].mean(axis=0)
    if np.dot(dend_c - soma_c, axis) < 0:
        axis = -axis
    return axis / np.linalg.norm(axis)


# --------------------------------------------------------------- Vm mapping
def nearest_values(points_um: np.ndarray, sample_points_um: np.ndarray,
                   sample_values: np.ndarray) -> np.ndarray:
    """Nearest-neighbor-map ``sample_values`` (defined at sparse simulated
    compartment centers) onto a denser set of points (typically SWC trace
    points) — for coloring a full traced skeleton by a handful of simulated
    segment values."""
    from scipy.spatial import cKDTree
    tree = cKDTree(sample_points_um)
    _, idx = tree.query(points_um)
    return np.asarray(sample_values)[idx]


# ---------------------------------------------------------- synthetic cells
def synthetic_branching_tree(n_generations: int = 4, branching: int = 2,
                             segment_len_um: float = 40.0,
                             segment_points: int = 4,
                             soma_radius_um: float = 10.0,
                             taper: float = 0.82,
                             seed: int = 0) -> SWCMorphology:
    """A procedurally-generated branching dendritic tree + a straight axon,
    purely geometric (no NEURON/mechanisms involved) — for exercising and
    testing the morphology/plotting code without any compiled model.

    Root (soma, type 1) at the origin; ``branching``-way dendritic
    bifurcations (type 3) for ``n_generations`` levels, each generation's
    segments shorter and thinner than its parent's (``taper``); one axon
    (type 2) running the -z direction from the soma.
    """
    rng = np.random.default_rng(seed)
    ids, types, pts, radii, parents = [1], [1], [np.zeros(3)], [soma_radius_um], [-1]

    def add_chain(start_pt, direction, length_um, radius_um, parent_id,
                  n_pts, kind):
        direction = direction / (np.linalg.norm(direction) + 1e-12)
        p = parent_id
        for k in range(1, n_pts + 1):
            pt = start_pt + direction * (length_um * k / n_pts)
            ids.append(len(ids) + 1)
            types.append(kind)
            pts.append(pt)
            radii.append(radius_um)
            parents.append(p)
            p = ids[-1]
        return pts[-1], p

    # axon: straight run, tapering
    tip, pid = add_chain(pts[0], np.array([0, 0, -1.0]),
                         segment_len_um * n_generations, soma_radius_um * 0.3,
                         parents_root := 1, segment_points * n_generations, 2)

    def grow(start_pt, direction, radius_um, gen, parent_id):
        if gen > n_generations:
            return
        tip, pid = add_chain(start_pt, direction, segment_len_um, radius_um,
                             parent_id, segment_points, 3)
        for _ in range(branching):
            jitter = rng.normal(scale=0.6, size=3)
            new_dir = direction + jitter
            grow(tip, new_dir, radius_um * taper, gen + 1, pid)

    for k in range(branching):
        ang = 2 * np.pi * k / branching
        d0 = np.array([np.cos(ang), np.sin(ang), 0.3])
        grow(pts[0], d0, soma_radius_um * 0.5, 1, 1)

    return SWCMorphology(
        ids=np.asarray(ids, dtype=np.int64),
        types=np.asarray(types, dtype=np.int64),
        xyz_um=np.stack(pts, axis=0),
        radius_um=np.asarray(radii, dtype=float),
        parent=np.asarray(parents, dtype=np.int64),
    )
